wipe = true
no-hooks = true
no-tests = true
no-auto-timestamps = true
no-rows-affected = true

[psql]
dbname = "jaunty"
host = "localhost"
port = 5430
user = "jaunty"
pass = "jaunty"
sslmode = "disable"
blacklist = ["schema_migrations"]